[build]
 target = "armv7-unknown-linux-musleabihf" # default target
#target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-ld"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"
